name: Trigger Mizuki Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Mizuki workflow_dispatch
        uses: peter-evans/workflow-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: Admilkk/Mizuki
          workflow: deploy.yml
          ref: master
